"""
routers/worker.py

POST /worker/register   - one-time worker account creation (saved in Postgres).
                           worker_id is auto-generated by the backend (not chosen by
                           the worker) and handed back in the response so they can
                           log in with it. Starts out unapproved (is_approved=False)
                           until an admin approves it.
POST /worker/login       - worker logs in, gets a token that expires after TOKEN_EXPIRY_HOURS.
                           Blocked with a 403 until the account has been approved by an admin.
GET  /worker/my-machines - returns only the machines this worker has been assigned.
GET  /worker/my-tips     - returns every knowledge entry this worker has personally
                           submitted, with each one's current status.
GET  /worker/profile     - returns the logged-in worker's own profile fields.
PUT  /worker/profile     - worker edits their own profile (name, phone, address,
                           and optionally their password with current_password confirmation).
"""

import re
import secrets
from fastapi import APIRouter, HTTPException, Depends
from sqlalchemy.orm import Session

from db import get_db
from models import Worker, WorkerSession, WorkerMachine
from schemas import WorkerRegisterRequest, WorkerLoginRequest, WorkerProfileUpdateRequest
from auth.security import hash_password, verify_password, make_expiry_time
from config import TOKEN_EXPIRY_HOURS
from auth.worker_auth import require_worker
from rag.chroma_store import collection

router = APIRouter(prefix="/worker", tags=["worker"])

_WORKER_ID_RE = re.compile(r"^W(\d+)$")


def generate_worker_id(db: Session) -> str:
    """
    Picks the next free "W<n>" worker_id, based on the highest numeric
    suffix currently in use (existing seed data starts at W101). Loops
    with a fresh uniqueness check in the rare case of a collision (e.g.
    a gap from a rejected/renamed worker) rather than trusting the count
    alone, and gives up after a bounded number of attempts rather than
    looping forever.
    """
    highest = 100
    for (existing_id,) in db.query(Worker.worker_id).all():
        m = _WORKER_ID_RE.match(existing_id or "")
        if m:
            highest = max(highest, int(m.group(1)))

    for _ in range(50):
        highest += 1
        candidate = f"W{highest}"
        if not db.query(Worker).filter(Worker.worker_id == candidate).first():
            return candidate

    raise HTTPException(status_code=500, detail="Could not generate a unique worker ID. Please try again.")


@router.post("/register")
def worker_register(req: WorkerRegisterRequest, db: Session = Depends(get_db)):
    """A worker creates their account once - password, name, and optional contact
    details. worker_id is auto-generated (never chosen by the worker) and returned
    so they can save it for logging in. Starts unapproved - is_approved defaults to
    False until an admin approves it."""
    worker_id = generate_worker_id(db)

    new_worker = Worker(
        worker_id=worker_id,
        password_hash=hash_password(req.password),
        name=req.name,
        phone_country_code=req.phone_country_code,
        phone_number=req.phone_number,
        address=req.address,
    )
    db.add(new_worker)
    db.commit()

    return {
        "status": "registered",
        "worker_id": worker_id,
        "name": req.name,
        "message": "Registration received. An admin must approve your account before you can log in.",
    }


@router.post("/login")
def worker_login(req: WorkerLoginRequest, db: Session = Depends(get_db)):
    """A worker logs in with their worker_id and password, and gets a token that expires after TOKEN_EXPIRY_HOURS.
    Blocked with a 403 if the account hasn't been approved by an admin yet."""
    worker = db.query(Worker).filter(Worker.worker_id == req.worker_id).first()
    if not worker:
        raise HTTPException(status_code=401, detail="Worker ID not found. Please register first.")

    if not verify_password(req.password, worker.password_hash):
        raise HTTPException(status_code=401, detail="Incorrect password.")

    if not worker.is_approved:
        raise HTTPException(status_code=403, detail="Your account is still waiting for admin approval.")

    token = secrets.token_hex(16)
    session = WorkerSession(token=token, worker_id=worker.worker_id, expires_at=make_expiry_time())
    db.add(session)
    db.commit()

    return {
        "token": token,
        "name": worker.name,
        "expires_in_hours": TOKEN_EXPIRY_HOURS,
        "message": "Login successful. Use this token in the Authorization header as 'Bearer <token>'.",
    }


@router.get("/my-machines")
def my_machines(worker: dict = Depends(require_worker), db: Session = Depends(get_db)):
    """Returns only the machines THIS logged-in worker has been assigned by admin."""
    assignments = db.query(WorkerMachine).filter(WorkerMachine.worker_id == worker["worker_id"]).all()
    return {"machine_ids": [a.machine_id for a in assignments]}


@router.get("/my-tips")
def my_tips(worker: dict = Depends(require_worker)):
    """
    Returns every knowledge entry this worker submitted, including
    video_url / image_url so the Library can show media.
    """
    import re
    results = collection.get(
        where={"worker_id": worker["worker_id"]},
        include=["documents", "metadatas"],
    )

    tips = []
    ids = results.get("ids") or []
    docs = results.get("documents") or []
    metas = results.get("metadatas") or []
    for i in range(len(ids)):
        meta = metas[i] or {}
        raw = docs[i] or ""
        # Tip body without long AI understanding blocks
        display = re.split(
            r"\n\s*\[(?:Video Understanding|Image Understanding|Transcript|Image Text)\]",
            raw,
            maxsplit=1,
        )[0].strip() or raw
        tips.append({
            "id": ids[i],
            "text": display,
            "full_text": raw,
            "machine_id": meta.get("machine_id"),
            "status": meta.get("status", "pending"),
            "video_url": meta.get("video_url") or None,
            "image_url": meta.get("image_url") or None,
            "created_at": meta.get("created_at") or meta.get("submitted_at") or None,
        })

    tips.sort(key=lambda t: t.get("created_at") or "", reverse=True)
    return {"tips": tips}

@router.get("/profile")
def get_my_profile(worker: dict = Depends(require_worker), db: Session = Depends(get_db)):
    """Returns the logged-in worker's own profile fields (never the password)."""
    w = db.query(Worker).filter(Worker.worker_id == worker["worker_id"]).first()
    if not w:
        raise HTTPException(status_code=404, detail="Worker not found.")

    return {
        "worker_id": w.worker_id,
        "name": w.name,
        "phone_country_code": w.phone_country_code,
        "phone_number": w.phone_number,
        "address": w.address,
    }


@router.put("/profile")
def update_my_profile(
    req: WorkerProfileUpdateRequest,
    worker: dict = Depends(require_worker),
    db: Session = Depends(get_db),
):
    """
    A worker updates their own profile. Only fields actually provided are
    changed. worker_id is never editable here - only an admin can rename it
    (see admin.py PUT /admin/workers/{worker_id}).

    Password change is opt-in: providing new_password without a matching
    current_password is rejected, so a worker can't be locked out by a
    stray/incomplete request, and no one else can silently change it for them.
    """
    w = db.query(Worker).filter(Worker.worker_id == worker["worker_id"]).first()
    if not w:
        raise HTTPException(status_code=404, detail="Worker not found.")

    if req.name is not None:
        w.name = req.name
    if req.phone_country_code is not None:
        w.phone_country_code = req.phone_country_code
    if req.phone_number is not None:
        w.phone_number = req.phone_number
    if req.address is not None:
        w.address = req.address

    if req.new_password:
        if not req.current_password:
            raise HTTPException(status_code=400, detail="Enter your current password to set a new one.")
        if not verify_password(req.current_password, w.password_hash):
            raise HTTPException(status_code=401, detail="Current password is incorrect.")
        w.password_hash = hash_password(req.new_password)

    db.commit()

    return {
        "status": "updated",
        "worker_id": w.worker_id,
        "name": w.name,
        "phone_country_code": w.phone_country_code,
        "phone_number": w.phone_number,
        "address": w.address,
    }