"""
schemas.py

Pydantic request models - what the frontend must send to each endpoint.
Kept in one file since they're small and every router needs a subset of them.
"""

from pydantic import BaseModel
from typing import Optional


class AskRequest(BaseModel):
    question: str
    machine_id: str


class AddKnowledgeRequest(BaseModel):
    text: str
    machine_id: str
    language_code: str = "en-IN"
    # No worker_name field - it's pulled automatically from the logged-in worker's account
    # language_code is only used to pick which language to phrase the spoken
    # confirmation in - it doesn't affect what gets stored.


class CheckKnowledgeRequest(BaseModel):
    text: str
    machine_id: str
    round: int = 1
    language_code: str = "en-IN"
    # round = which clarification round this check call represents.
    # round 1 = first attempt. round 2 = after the worker answered one
    # clarifying question. The backend forces completion at round >= 2,
    # regardless of what the model thinks, to cap the back-and-forth.
    # language_code = the language Sarvam STT detected when the worker
    # spoke the tip (or the frontend's default, if typed instead of
    # spoken) - used so any clarifying question comes back phrased in
    # the same language, not guessed by the model from the text.


class AdminLoginRequest(BaseModel):
    username: str
    password: str


class WorkerRegisterRequest(BaseModel):
    # worker_id is NOT accepted here - it's auto-generated by the backend
    # (see worker.py generate_worker_id) and handed back in the response.
    password: str
    name: str
    phone_country_code: str = "+91"
    phone_number: Optional[str] = None
    address: Optional[str] = None


class WorkerLoginRequest(BaseModel):
    worker_id: str
    password: str


class WorkerProfileUpdateRequest(BaseModel):
    """PUT /worker/profile - a worker editing their own profile.
    Every field optional; only the ones provided get changed.
    Password change requires current_password to verify identity first -
    new_password alone is ignored without it."""
    name: Optional[str] = None
    phone_country_code: Optional[str] = None
    phone_number: Optional[str] = None
    address: Optional[str] = None
    current_password: Optional[str] = None
    new_password: Optional[str] = None


class AdminProfileUpdateRequest(BaseModel):
    """PUT /admin/profile - admin editing their own display name.
    No password field - login credentials are never editable here."""
    name: str


class AdminUpdateWorkerRequest(BaseModel):
    """PUT /admin/workers/{worker_id} - admin editing a worker's profile.
    Every field optional; only the ones provided get changed. No password
    field - admin can never set or view a worker's password. new_worker_id,
    if given and different, renames the worker's login ID (cascades to
    every table that references it - see admin.py)."""
    new_worker_id: Optional[str] = None
    name: Optional[str] = None
    phone_country_code: Optional[str] = None
    phone_number: Optional[str] = None
    address: Optional[str] = None

class AssignMachineRequest(BaseModel):
    worker_id: str
    machine_id: str


class EditEntryRequest(BaseModel):
    text: str


class StartInterviewRequest(BaseModel):
    machine_id: str
    language_code: str = "en-IN"
    # If true, any existing in_progress/paused session for this worker+
    # machine is abandoned and a brand-new one is created instead of
    # resuming it. Set when the worker explicitly chooses "Start fresh"
    # after being shown a resume/fresh choice (see GET /interview/check).
    fresh: bool = False
    # language_code is the worker's preferred spoken language, picked
    # before the interview starts (unlike Add Tip, where it's detected
    # from the first recording) - since the opening question itself
    # needs to be spoken in some language before we've heard the worker
    # say anything. Sarvam STT may still detect a different language
    # from their actual answers, in which case later turns follow that
    # instead - see routers/interview.py.


class CreateTicketRequest(BaseModel):
    title: str
    description: str
    machine_id: Optional[str] = None
    priority: str = "Medium"  # Low / Medium / High

class UpdateTicketRequest(BaseModel):
    status: str  # Open / In Progress / Resolved / Closed


# ---------- Safety Measures ----------

class CreateSafetyMeasureRequest(BaseModel):
    machine_id: str
    title: str
    content: str
    sort_order: int = 1
    language_code: str = "en-IN"
    is_active: bool = True


class UpdateSafetyMeasureRequest(BaseModel):
    title: Optional[str] = None
    content: Optional[str] = None
    sort_order: Optional[int] = None
    language_code: Optional[str] = None
    is_active: Optional[bool] = None


class ReorderSafetyMeasureItem(BaseModel):
    id: str
    sort_order: int


class ReorderSafetyMeasuresRequest(BaseModel):
    items: list[ReorderSafetyMeasureItem]


class CompleteSafetyRequest(BaseModel):
    language_code: str = "en-IN"